Removed edit and delete buttons
citrineos/citrineos-operator-ui pull request #62
Opened 2024-11-11 19:08 UTC by deye9

2024-11-18 14:09 UTC, ChrisWeissmann requested changes

2024-11-18 14:09 UTC, ChrisWeissmann commented on src/pages/certificates/index.tsx
> +const CERTIFICATES_API_URL = '/data/certificates/certificateChain';
Seems something is off under the hood, when I run this and test it, seems the FE is making a http request to `ocpp/data/certificates/...`

2024-11-18 14:22 UTC, ChrisWeissmann commented
Could you also run the linter and formatter? Maybe automatically enable in your IDE.
Also please fix the conflicts :)

2025-01-27 17:31 UTC, thanaParis approved these changes
approved!

2025-01-27 17:32 UTC, merged